# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8313823622e3fb4b6fa6318054924f2126876903bf50cd01a3266076d3a9e4bdb99e553f738fb5865f6b7e324ac3d659f84d5dc5318b21c042221b9d78ac13d8

test:
  secret_key_base: af127996ca74fb95014eb670f977718ee678cce8d77c1d09834a05c5639634ffb4e2ee0930e34c45d6d6df93c3ccb679746f98241bf2bd736aa7ce07507717ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
